#!/usr/bin/env python


from pathlib import Path

from tracer import DEFAULT_BASE_DIR, check_default_base_dir
from tracer import TracerGraph


if check_default_base_dir():
    tg = TracerGraph(str(Path(DEFAULT_BASE_DIR) / Path('merge.log')))
    tg.plot_all(DEFAULT_BASE_DIR)

else:
    print(f'Default directory does NOT exist: "{DEFAULT_BASE_DIR}"')
